/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedArchivedRouteImport } from './routes/_authenticated/archived'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPurchasedRouteImport } from './routes/_authenticated/purchased'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections.index'
import { Route as AuthenticatedCollectionsIdRouteImport } from './routes/_authenticated/collections.$id'
import { Route as AuthenticatedItemsIdRouteImport } from './routes/_authenticated/items.$id'
import { Route as AuthenticatedItemsNewRouteImport } from './routes/_authenticated/items.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedArchivedRoute = AuthenticatedArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasedRoute = AuthenticatedPurchasedRouteImport.update({
  id: '/purchased',
  path: '/purchased',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionsIdRoute =
  AuthenticatedCollectionsIdRouteImport.update({
    id: '/collections/$id',
    path: '/collections/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedItemsIdRoute = AuthenticatedItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItemsNewRoute = AuthenticatedItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archived': typeof AuthenticatedArchivedRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/purchased': typeof AuthenticatedPurchasedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/items/$id': typeof AuthenticatedItemsIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/collections/': typeof AuthenticatedCollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/archived': typeof AuthenticatedArchivedRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/purchased': typeof AuthenticatedPurchasedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/items/$id': typeof AuthenticatedItemsIdRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/archived': typeof AuthenticatedArchivedRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/purchased': typeof AuthenticatedPurchasedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/collections/$id': typeof AuthenticatedCollectionsIdRoute
  '/_authenticated/items/$id': typeof AuthenticatedItemsIdRoute
  '/_authenticated/items/new': typeof AuthenticatedItemsNewRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/archived'
    | '/categories'
    | '/dashboard'
    | '/purchased'
    | '/settings'
    | '/collections/$id'
    | '/items/$id'
    | '/items/new'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/archived'
    | '/categories'
    | '/dashboard'
    | '/purchased'
    | '/settings'
    | '/collections/$id'
    | '/items/$id'
    | '/items/new'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/archived'
    | '/_authenticated/categories'
    | '/_authenticated/dashboard'
    | '/_authenticated/purchased'
    | '/_authenticated/settings'
    | '/_authenticated/collections/$id'
    | '/_authenticated/items/$id'
    | '/_authenticated/items/new'
    | '/_authenticated/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/archived': {
      id: '/_authenticated/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof AuthenticatedArchivedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchased': {
      id: '/_authenticated/purchased'
      path: '/purchased'
      fullPath: '/purchased'
      preLoaderRoute: typeof AuthenticatedPurchasedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections/$id': {
      id: '/_authenticated/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AuthenticatedCollectionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items/$id': {
      id: '/_authenticated/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof AuthenticatedItemsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/items/new': {
      id: '/_authenticated/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedItemsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArchivedRoute: typeof AuthenticatedArchivedRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPurchasedRoute: typeof AuthenticatedPurchasedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCollectionsIdRoute: typeof AuthenticatedCollectionsIdRoute
  AuthenticatedItemsIdRoute: typeof AuthenticatedItemsIdRoute
  AuthenticatedItemsNewRoute: typeof AuthenticatedItemsNewRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArchivedRoute: AuthenticatedArchivedRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPurchasedRoute: AuthenticatedPurchasedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCollectionsIdRoute: AuthenticatedCollectionsIdRoute,
  AuthenticatedItemsIdRoute: AuthenticatedItemsIdRoute,
  AuthenticatedItemsNewRoute: AuthenticatedItemsNewRoute,
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
